### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by ehsansabet** [tahaghafuri/html-css-2#1]
Hi,

- Please don't use inline css
`<a class="ha" style="color: dodgerblue;" href="#">صفحه اصلی</a>`
` <h4 style="margin: 0;text-align: center;font-size: 20px;color: gray;padding-right: 130px;">فوق تخصص در تمام زمینه های کاری</h4>`

- Tag `<center>` Not Supported in HTML5.([w3schools](https://www.w3schools.com/tags/tag_center.asp))

- When naming a class, please use meaningful names. [(BEM)](https://css-tricks.ir/tutorial/%D9%85%D8%B9%D8%B1%D9%81%DB%8C-%D8%B1%D9%88%D8%B4-bem-%D8%A8%D8%B1%D8%A7%DB%8C-%D9%86%D8%A7%D9%85%DA%AF%D8%B0%D8%A7%D8%B1%DB%8C-%DA%A9%D9%84%D8%A7%D8%B3-%D9%87%D8%A7/)

- In `<img>` tags do not use the `alt` property.
-

**Comment by tahaghafuri** [comment]
All Issues Fixed
